theme: jekyll-theme-slate
title: Mon Wiki
description: Wiki structuré et facile à naviguer
lang: fr

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

show_downloads: false
